name: Build

on:
  pull_request:
  push:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '12.3.Rel1'

    - name: Checkout pico-sdk
      run: |
        git clone --depth 1 -b develop https://github.com/raspberrypi/pico-sdk ~/pico-sdk
        echo >> $GITHUB_ENV PICO_SDK_PATH=~/pico-sdk
        # checkout tinyusb in pico-sdk and switch to master branch
        git -C ~/pico-sdk submodule update --init
        git -C ~/pico-sdk/lib/tinyusb fetch
        git -C ~/pico-sdk/lib/tinyusb checkout master

    - name: Build
      run: |
        cd examples
        mkdir build
        cd build
        cmake ..
        make

    - uses: actions/upload-artifact@v3
      with:
        name: example_binaries
        path: |
          examples/build/usb_device/usb_device.uf2
          examples/build/usb_device/usb_device.hex
          examples/build/capture_hid_report/capture_hid_report.uf2
          examples/build/capture_hid_report/capture_hid_report.hex
          examples/build/host_hid_to_device_cdc/host_hid_to_device_cdc.uf2
          examples/build/host_hid_to_device_cdc/host_hid_to_device_cdc.hex
